// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2619754594);
}

/**
 * GetUpdatePolicy 保留给现有前端调用，应用只支持便携更新。
 */
export function GetUpdatePolicy(): $CancellablePromise<string> {
    return $Call.ByID(728611828);
}
