// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcknowledgeLogRetentionNotice 清除日志保留策略的一次性提示。
 * 前端展示过提示后调用。
 */
export function AcknowledgeLogRetentionNotice(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1031303574).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAppSettings returns the persisted app settings or defaults if the file does not exist.
 */
export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(55540836).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGlobalProxyConfig(): $CancellablePromise<$models.ProxyConfig> {
    return $Call.ByID(2080592793).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetProviderProxyConfig(enabled: boolean): $CancellablePromise<$models.ProxyConfig> {
    return $Call.ByID(3863070771, enabled).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveAppSettings persists the provided settings to disk.
 */
export function SaveAppSettings(settings: $models.AppSettings): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(39874379, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

export function TestGlobalProxy(protocol: string, host: string, port: number): $CancellablePromise<$models.ProxyTestResult> {
    return $Call.ByID(535813047, protocol, host, port).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $models.ProxyConfig.createFrom;
const $$createType2 = $models.ProxyTestResult.createFrom;
