// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClaudeSettingsService 管理 ~/.claude/settings.json 的代理启停与直连应用。
 * 
 * 具体逻辑由 jsonProxyPlatform 通用实现承接（见 json_proxy_settings.go），
 * 这里只保留对外方法签名——它们注册进 Wails 绑定供前端调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySingleProvider 参数是 int 而非 int64：这是既有的对外绑定签名，
 * 前端依赖它，改动会连带改前端，因此保留。
 */
export function ApplySingleProvider(providerID: number): $CancellablePromise<void> {
    return $Call.ByID(2558916630, providerID);
}

export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(1555695857);
}

export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(78884094);
}

export function GetDirectAppliedProviderID(): $CancellablePromise<number | null> {
    return $Call.ByID(2243597647);
}

export function ProxyStatus(): $CancellablePromise<$models.ClaudeProxyStatus> {
    return $Call.ByID(4279409145).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ClaudeProxyStatus.createFrom;
