// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectivityTestService 提供供应商编辑页的单次连接测试。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * TestProviderManual 手动做供应商延迟检查（供前端按钮调用）
 */
export function TestProviderManual(platform: string, apiURL: string, apiKey: string, endpoint: string, authType: string, proxyEnabled: boolean): $CancellablePromise<$models.ManualTestResult> {
    return $Call.ByID(2146278070, platform, apiURL, apiKey, endpoint, authType, proxyEnabled).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ManualTestResult.createFrom;
