// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsoleService 控制台日志服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLogs 清空日志
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(3175582973);
}

/**
 * GetLogs 获取所有日志
 */
export function GetLogs(): $CancellablePromise<$models.ConsoleLog[]> {
    return $Call.ByID(1697160384).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLogsSince(afterSequence: number, limit: number): $CancellablePromise<$models.ConsoleLogBatch> {
    return $Call.ByID(159937930, afterSequence, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRecentLogs 获取最近 N 条日志
 */
export function GetRecentLogs(count: number): $CancellablePromise<$models.ConsoleLog[]> {
    return $Call.ByID(2165472563, count).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConsoleLog.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ConsoleLogBatch.createFrom;
