// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySingleProvider 直连应用单一供应商（仅在代理关闭时可用）
 */
export function ApplySingleProvider(providerID: number): $CancellablePromise<void> {
    return $Call.ByID(1100656933, providerID);
}

export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(3874840628);
}

export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(3547944929);
}

/**
 * GetDirectAppliedProviderID 返回当前直连应用的 Provider ID
 */
export function GetDirectAppliedProviderID(): $CancellablePromise<number | null> {
    return $Call.ByID(2495593026);
}

export function ProxyStatus(): $CancellablePromise<$models.DeepSeekCodeProxyStatus> {
    return $Call.ByID(1110070922).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DeepSeekCodeProxyStatus.createFrom;
