// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetPreferences(): $CancellablePromise<$models.FrontendPreferences> {
    return $Call.ByID(3288485300).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SavePreferences(prefs: $models.FrontendPreferences): $CancellablePromise<$models.FrontendPreferences> {
    return $Call.ByID(3225543171, prefs).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FrontendPreferences.createFrom;
