// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAccounts(): $CancellablePromise<$models.GeminiCliAccount[]> {
    return $Call.ByID(2808325624).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetOAuthLoginStatus(sessionID: string): $CancellablePromise<$models.GeminiCliOAuthLoginStatus | null> {
    return $Call.ByID(1299289834, sessionID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RefreshAccount 只在 oauth_creds.json 提供标准 refresh_token 和 token URL 时执行刷新。
 * 缺少刷新材料时返回错误，不把重新读取旧 token 伪装成刷新成功。
 */
export function RefreshAccount(accountID: string): $CancellablePromise<$models.GeminiCliAccount | null> {
    return $Call.ByID(1218717878, accountID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RefreshQuota(accountID: string): $CancellablePromise<$models.GeminiCliQuotaSnapshot | null> {
    return $Call.ByID(2855241225, accountID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1459314004);
}

/**
 * StartOAuthLogin starts a loopback OAuth callback. The OAuth client ID and
 * optional secret are process configuration, never persisted or returned to UI.
 */
export function StartOAuthLogin(): $CancellablePromise<$models.GeminiCliOAuthLogin | null> {
    return $Call.ByID(2472935272).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2684953360);
}

// Private type creation functions
const $$createType0 = $models.GeminiCliAccount.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.GeminiCliOAuthLoginStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Nullable($$createType0);
const $$createType5 = $models.GeminiCliQuotaSnapshot.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.GeminiCliOAuthLogin.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
