// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetCatalog(providerID: string, forceRefresh: boolean): $CancellablePromise<$models.GeminiModelCatalog | null> {
    return $Call.ByID(1508348349, providerID, forceRefresh).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetModelDetail(providerID: string, modelID: string): $CancellablePromise<$models.GeminiModel | null> {
    return $Call.ByID(3980693106, providerID, modelID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2316008162);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1329032418);
}

// Private type creation functions
const $$createType0 = $models.GeminiModelCatalog.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GeminiModel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
