// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AbandonManagement(): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(652357517).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ApplyOAuthAccount(accountID: string): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(432377397, accountID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CancelDeviceCode(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3162349512, sessionID);
}

export function DisableManagement(): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(466971976).then(($result: any) => {
        return $$createType0($result);
    });
}

export function EnableRelay(): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(2362266791).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDeviceCodeStatus(sessionID: string): $CancellablePromise<$models.GrokDeviceAuthStatus> {
    return $Call.ByID(1624921526, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetStatus(): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(2997488817).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportCurrentOAuthAccount(): $CancellablePromise<$models.GrokOAuthImportResult> {
    return $Call.ByID(1420990143).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ImportOAuthDirectory(directory: string): $CancellablePromise<$models.GrokOAuthImportResult[]> {
    return $Call.ByID(221289690, directory).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportOAuthFiles(paths: string[]): $CancellablePromise<$models.GrokOAuthImportResult[]> {
    return $Call.ByID(676947346, paths).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListOAuthAccounts(): $CancellablePromise<$models.GrokOAuthAccountDTO[]> {
    return $Call.ByID(2332971284).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ReapplyCurrentMode(): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(611557934).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RefreshAllOAuthQuotas(force: boolean): $CancellablePromise<$models.GrokOAuthRefreshResult[]> {
    return $Call.ByID(605766687, force).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RefreshOAuthAccount(accountID: string): $CancellablePromise<$models.GrokOAuthAccountDTO> {
    return $Call.ByID(3641553550, accountID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RefreshOAuthQuota(accountID: string, force: boolean): $CancellablePromise<$models.GrokOAuthAccountDTO> {
    return $Call.ByID(1636902737, accountID, force).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RemoveOAuthAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(2337900579, accountID);
}

export function SetCustomDirectory(directory: string): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(39441219, directory).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1815659727);
}

export function StartDeviceCode(): $CancellablePromise<$models.GrokDeviceAuthStartResult> {
    return $Call.ByID(2866732340).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1575100565);
}

// Private type creation functions
const $$createType0 = $models.GrokRuntimeStatus.createFrom;
const $$createType1 = $models.GrokDeviceAuthStatus.createFrom;
const $$createType2 = $models.GrokOAuthImportResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.GrokOAuthAccountDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.GrokOAuthRefreshResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.GrokDeviceAuthStartResult.createFrom;
