// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportCurrentProjectDirectory(path: string): $CancellablePromise<$models.ProjectTransferResult> {
    return $Call.ByID(701797226, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProjectTransferInfo(): $CancellablePromise<$models.ProjectTransferInfo> {
    return $Call.ByID(1092213369).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetStatus(): $CancellablePromise<$models.ConfigImportStatus> {
    return $Call.ByID(2109164227).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ImportAll 从默认路径导入 cc-switch 配置
 */
export function ImportAll(): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(124174517).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportCurrentProjectDirectory(path: string): $CancellablePromise<$models.ProjectTransferResult> {
    return $Call.ByID(4017468279, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromPath 从指定路径导入 cc-switch 配置
 */
export function ImportFromPath(path: string): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(2519238097, path).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportLegacyProjectDirectory(path: string): $CancellablePromise<$models.ProjectTransferResult> {
    return $Call.ByID(1344830293, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportMCPServers 将服务器写入配置，并同步到 Claude/Codex。
 * strategy:
 * - "skip": 已存在则跳过
 * - "overwrite": 用导入内容更新（保留既有 enable_platform 的并集）
 */
export function ImportMCPServers(servers: $models.MCPServer[], strategy: string): $CancellablePromise<number> {
    return $Call.ByID(3450963826, servers, strategy);
}

export function ImportMCPServersForPlatform(servers: $models.MCPServer[], strategy: string, platform: string): $CancellablePromise<number> {
    return $Call.ByID(1179559462, servers, strategy, platform);
}

/**
 * IsFirstRun 检查是否首次使用（用于显示导入提示）
 */
export function IsFirstRun(): $CancellablePromise<boolean> {
    return $Call.ByID(4249749624);
}

/**
 * MarkFirstRunDone 标记首次使用已完成（不再显示导入提示）
 */
export function MarkFirstRunDone(): $CancellablePromise<void> {
    return $Call.ByID(838327945);
}

/**
 * ParseMCPJSON 解析用户粘贴的 MCP JSON，返回可供前端预览/选择的结构化结果。
 * 支持格式：
 * 1) Claude Desktop: {"mcpServers": {"name": {...}}}
 * 2) 数组: [{"name": "...", ...}, ...]
 * 3) 单服务器: {"command": "...", "args": [...] }（name 可选，缺失时 needName=true）
 * 4) 服务器映射: {"name": {...}, "name2": {...}}
 */
export function ParseMCPJSON(jsonStr: string): $CancellablePromise<$models.MCPParseResult | null> {
    return $Call.ByID(489842720, jsonStr).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ParseMCPJSONForPlatform(jsonStr: string, platform: string): $CancellablePromise<$models.MCPParseResult | null> {
    return $Call.ByID(963746064, jsonStr, platform).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3119656637);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2083779375);
}

// Private type creation functions
const $$createType0 = $models.ProjectTransferResult.createFrom;
const $$createType1 = $models.ProjectTransferInfo.createFrom;
const $$createType2 = $models.ConfigImportStatus.createFrom;
const $$createType3 = $models.ConfigImportResult.createFrom;
const $$createType4 = $models.MCPParseResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
