// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OAuthAccountService owns OAuth account metadata and secrets separately from Provider.
 * It intentionally keeps the portable file backend so the desktop app does not require
 * an OS-specific keychain to move between machines.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyClaudeAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(1118893413, id);
}

export function ApplyCodexAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(1194941426, id);
}

export function CancelOAuthLogin(loginID: string): $CancellablePromise<void> {
    return $Call.ByID(4151113610, loginID);
}

export function ClearClaudeAccount(): $CancellablePromise<void> {
    return $Call.ByID(3654428886);
}

export function ClearCodexAccount(): $CancellablePromise<void> {
    return $Call.ByID(3167345935);
}

export function CompleteClaudeOAuth(loginID: string, callback: string): $CancellablePromise<$models.OAuthAccountSummary | null> {
    return $Call.ByID(1665986288, loginID, callback).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CompleteCodexOAuth(loginID: string, callback: string): $CancellablePromise<$models.OAuthAccountSummary | null> {
    return $Call.ByID(614927797, loginID, callback).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(2930681506, id);
}

/**
 * ImportClaudeLocal reads Claude Code's two OAuth snapshots without importing
 * Desktop cookies or the browser profile.
 */
export function ImportClaudeLocal(): $CancellablePromise<$models.OAuthImportResult | null> {
    return $Call.ByID(554851202).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ImportCodexLocal imports only the official OAuth tokens under ~/.codex/auth.json.
 * OPENAI_API_KEY-only auth and agentIdentity are rejected by the normalizer.
 */
export function ImportCodexLocal(): $CancellablePromise<$models.OAuthImportResult | null> {
    return $Call.ByID(1377490827).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportJSON(request: $models.OAuthImportRequest): $CancellablePromise<$models.OAuthImportResult | null> {
    return $Call.ByID(1862389503, request).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListAccounts(platform: string): $CancellablePromise<$models.OAuthAccountSummary[]> {
    return $Call.ByID(4095160440, platform).then(($result: any) => {
        return $$createType4($result);
    });
}

export function PollCodexDeviceCode(loginID: string): $CancellablePromise<$models.OAuthLoginStatus | null> {
    return $Call.ByID(1464180343, loginID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function RefreshAccount(id: string): $CancellablePromise<$models.OAuthAccountSummary | null> {
    return $Call.ByID(3582368114, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RefreshQuota(id: string): $CancellablePromise<$models.OAuthAccountSummary | null> {
    return $Call.ByID(56757645, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(4038274464);
}

/**
 * StartClaudeOAuth starts a manual callback PKCE session. The callback URL is intentionally
 * returned for copy/paste because a desktop Wails app cannot assume a free local callback port.
 */
export function StartClaudeOAuth(): $CancellablePromise<$models.OAuthLoginStart | null> {
    return $Call.ByID(38635737).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * StartCodexDeviceCode starts the OpenAI device flow used by official Codex CLI.
 */
export function StartCodexDeviceCode(): $CancellablePromise<$models.OAuthLoginStart | null> {
    return $Call.ByID(3982011164).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * StartCodexOAuth starts the official browser PKCE flow. The callback URL can be pasted into
 * CompleteCodexOAuth; no listener is opened implicitly.
 */
export function StartCodexOAuth(): $CancellablePromise<$models.OAuthLoginStart | null> {
    return $Call.ByID(3839438918).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1074532836);
}

// Private type creation functions
const $$createType0 = $models.OAuthAccountSummary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.OAuthImportResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.OAuthLoginStatus.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.OAuthLoginStart.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
