// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyProvider(providerKey: string): $CancellablePromise<$models.OpenCodeApplyResult> {
    return $Call.ByID(620282484, providerKey).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClaimMCPServer(key: string): $CancellablePromise<$models.OpenCodeMCPServerInfo[]> {
    return $Call.ByID(3028797136, key).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteMCPServer(key: string): $CancellablePromise<$models.OpenCodeMCPServerInfo[]> {
    return $Call.ByID(699676559, key).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteProvider(providerKey: string): $CancellablePromise<void> {
    return $Call.ByID(1181751877, providerKey);
}

export function Diagnostics(): $CancellablePromise<$models.OpenCodeDiagnostics> {
    return $Call.ByID(1553626481).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetConfigPathInfo(): $CancellablePromise<$models.OpenCodeConfigInfo> {
    return $Call.ByID(3560139132).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetGlobalPrompt(): $CancellablePromise<$models.OpenCodePromptInfo> {
    return $Call.ByID(2106498372).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ImportLiveProviders(): $CancellablePromise<$models.OpenCodeProviderInfo[]> {
    return $Call.ByID(3829220802).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListMCPServers(): $CancellablePromise<$models.OpenCodeMCPServerInfo[]> {
    return $Call.ByID(2739586895).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListWSLTargets(): $CancellablePromise<$models.OpenCodeWSLTargetInfo[]> {
    return $Call.ByID(537918287).then(($result: any) => {
        return $$createType9($result);
    });
}

export function RenameProviderKey(oldKey: string, newKey: string): $CancellablePromise<void> {
    return $Call.ByID(2605765863, oldKey, newKey);
}

export function RestoreProvider(providerKey: string): $CancellablePromise<$models.OpenCodeApplyResult> {
    return $Call.ByID(3586308474, providerKey).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveGlobalPrompt(content: string, expectedHash: string): $CancellablePromise<$models.OpenCodePromptInfo> {
    return $Call.ByID(2553048575, content, expectedHash).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveMCPServer(input: $models.OpenCodeMCPServerInput): $CancellablePromise<$models.OpenCodeMCPServerInfo[]> {
    return $Call.ByID(3797189877, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SaveProvider(input: $models.OpenCodeProviderInput): $CancellablePromise<$models.OpenCodeProviderInfo> {
    return $Call.ByID(3766937619, input).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SetConfigPath(input: $models.OpenCodePathInput): $CancellablePromise<$models.OpenCodeConfigInfo> {
    return $Call.ByID(2472564268, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetDefaultModels(input: $models.OpenCodeDefaultModelsInput): $CancellablePromise<$models.OpenCodeConfigSnapshot> {
    return $Call.ByID(395136204, input).then(($result: any) => {
        return $$createType10($result);
    });
}

export function Snapshot(): $CancellablePromise<$models.OpenCodeConfigSnapshot> {
    return $Call.ByID(1002181451).then(($result: any) => {
        return $$createType10($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1833019225);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3833518131);
}

export function SyncWSLConfig(input: $models.OpenCodeWSLSyncInput): $CancellablePromise<$models.OpenCodeWSLSyncResult> {
    return $Call.ByID(1134285272, input).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OpenCodeApplyResult.createFrom;
const $$createType1 = $models.OpenCodeMCPServerInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.OpenCodeDiagnostics.createFrom;
const $$createType4 = $models.OpenCodeConfigInfo.createFrom;
const $$createType5 = $models.OpenCodePromptInfo.createFrom;
const $$createType6 = $models.OpenCodeProviderInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.OpenCodeWSLTargetInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.OpenCodeConfigSnapshot.createFrom;
const $$createType11 = $models.OpenCodeWSLSyncResult.createFrom;
