// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(293752948);
}

export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(894580513);
}

export function PreviewModelsJSON(input: $models.PiModelsPreviewRequest): $CancellablePromise<$models.PiModelsPreviewResult> {
    return $Call.ByID(3412279864, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ProxyStatus(): $CancellablePromise<$models.ClaudeProxyStatus> {
    return $Call.ByID(2361587658).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SyncGateway(): $CancellablePromise<void> {
    return $Call.ByID(2571930579);
}

export function SyncGatewayIfEnabled(): $CancellablePromise<void> {
    return $Call.ByID(3504247529);
}

// Private type creation functions
const $$createType0 = $models.PiModelsPreviewResult.createFrom;
const $$createType1 = $models.ClaudeProxyStatus.createFrom;
