// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddBuiltinModelToPlatform(input: $models.PiBuiltinModelAddRequest): $CancellablePromise<$models.PiBuiltinModelAddResult> {
    return $Call.ByID(2040100849, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ApplyPlatformModeChange(plan: $models.PiPlatformChangePlan): $CancellablePromise<void> {
    return $Call.ByID(4089509040, plan);
}

export function BuiltinModelsCatalog(forceRefresh: boolean): $CancellablePromise<$models.PiBuiltinCatalogSnapshot> {
    return $Call.ByID(3232376504, forceRefresh).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateModelsProvider(input: $models.PiModelsProviderTemplate): $CancellablePromise<void> {
    return $Call.ByID(3033850315, input);
}

export function DeleteModelsProvider(id: string, expectedFingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(2846090288, id, expectedFingerprint);
}

export function DisablePlatformProxy(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(132977601, providerID);
}

export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(293752948);
}

export function EnablePlatformProxy(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(1945348056, providerID);
}

export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(894580513);
}

export function GetModelsProvider(id: string): $CancellablePromise<$models.PiModelsProviderTemplate> {
    return $Call.ByID(2421562723, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPlatformConflict(providerID: string): $CancellablePromise<$models.PiPlatformConflictDetail> {
    return $Call.ByID(3901885365, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetSupplier(providerID: number): $CancellablePromise<$models.Provider> {
    return $Call.ByID(2510573228, providerID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function InitializeDefaultModels(expectedRevision: string): $CancellablePromise<void> {
    return $Call.ByID(1542517177, expectedRevision);
}

export function MigrateLegacyGateway(expectedRevision: string): $CancellablePromise<void> {
    return $Call.ByID(948378112, expectedRevision);
}

export function ModelsCatalog(): $CancellablePromise<$models.PiModelsCatalogSnapshot> {
    return $Call.ByID(1386777041).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PlatformProxyStatus(providerID: string): $CancellablePromise<$models.PiPlatformProxyStatus> {
    return $Call.ByID(762802391, providerID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function PreviewModelsJSON(input: $models.PiModelsPreviewRequest): $CancellablePromise<$models.PiModelsPreviewResult> {
    return $Call.ByID(3412279864, input).then(($result: any) => {
        return $$createType7($result);
    });
}

export function PreviewPlatformModeChange(providerID: string, targetMode: string): $CancellablePromise<$models.PiPlatformChangePlan> {
    return $Call.ByID(4273163056, providerID, targetMode).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ProxyStatus(): $CancellablePromise<$models.ClaudeProxyStatus> {
    return $Call.ByID(2361587658).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * RenameModelsProvider changes the models.json Provider key and every
 * code-switch-R/Pi reference that uses that key as platform identity.
 */
export function RenameModelsProvider(originalID: string, input: $models.PiModelsProviderTemplate): $CancellablePromise<void> {
    return $Call.ByID(2728880249, originalID, input);
}

export function ResolvePlatformConflict(providerID: string, action: string, expectedRevision: string): $CancellablePromise<void> {
    return $Call.ByID(1644568645, providerID, action, expectedRevision);
}

export function RuntimeSnapshot(): $CancellablePromise<$models.PiRuntimeSnapshot> {
    return $Call.ByID(2024724712).then(($result: any) => {
        return $$createType10($result);
    });
}

export function SavePlatformOrder(providerIDs: string[], expectedRevision: string): $CancellablePromise<void> {
    return $Call.ByID(1648375802, providerIDs, expectedRevision);
}

export function SaveSupplierMutation(input: $models.PiSupplierMutationRequest): $CancellablePromise<$models.PiSupplierMutationResult> {
    return $Call.ByID(1690937910, input).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SaveSupplierOrder(platformID: string, providerIDs: number[], expectedRevision: string): $CancellablePromise<void> {
    return $Call.ByID(2572777003, platformID, providerIDs, expectedRevision);
}

/**
 * SetDebugLogging persists the Pi page switch and updates the relay hot path.
 */
export function SetDebugLogging(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4480512, enabled);
}

export function SyncGateway(): $CancellablePromise<void> {
    return $Call.ByID(2571930579);
}

export function SyncGatewayIfEnabled(): $CancellablePromise<void> {
    return $Call.ByID(3504247529);
}

export function UpdateModelsProvider(input: $models.PiModelsProviderTemplate): $CancellablePromise<void> {
    return $Call.ByID(4201432918, input);
}

// Private type creation functions
const $$createType0 = $models.PiBuiltinModelAddResult.createFrom;
const $$createType1 = $models.PiBuiltinCatalogSnapshot.createFrom;
const $$createType2 = $models.PiModelsProviderTemplate.createFrom;
const $$createType3 = $models.PiPlatformConflictDetail.createFrom;
const $$createType4 = $models.Provider.createFrom;
const $$createType5 = $models.PiModelsCatalogSnapshot.createFrom;
const $$createType6 = $models.PiPlatformProxyStatus.createFrom;
const $$createType7 = $models.PiModelsPreviewResult.createFrom;
const $$createType8 = $models.PiPlatformChangePlan.createFrom;
const $$createType9 = $models.ClaudeProxyStatus.createFrom;
const $$createType10 = $models.PiRuntimeSnapshot.createFrom;
const $$createType11 = $models.PiSupplierMutationResult.createFrom;
