// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteCustomPricingRule(id: string, expectedRevision: string): $CancellablePromise<void> {
    return $Call.ByID(1742201806, id, expectedRevision);
}

export function GetBuiltinPricingDetail(model: string): $CancellablePromise<$models.PricingBuiltinDetail> {
    return $Call.ByID(1215038488, model).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetPricingOverview(): $CancellablePromise<$models.PricingOverview> {
    return $Call.ByID(3201450779).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListBuiltinPricing(query: string, provider: string, mode: string, coverage: string, page: number, pageSize: number): $CancellablePromise<$models.PricingBuiltinPage> {
    return $Call.ByID(861382233, query, provider, mode, coverage, page, pageSize).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListCustomPricingRules(): $CancellablePromise<$models.PricingCustomRule[]> {
    return $Call.ByID(986935496).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ReorderCustomPricingRules(ids: string[], expectedRevision: string): $CancellablePromise<void> {
    return $Call.ByID(111111251, ids, expectedRevision);
}

export function SaveCustomPricingRule(rule: $models.PricingCustomRule, expectedRevision: string): $CancellablePromise<$models.PricingCustomRule> {
    return $Call.ByID(3218430748, rule, expectedRevision).then(($result: any) => {
        return $$createType3($result);
    });
}

export function TestPricingMatch(model: string): $CancellablePromise<$models.PricingMatchResult> {
    return $Call.ByID(2932370125, model).then(($result: any) => {
        return $$createType5($result);
    });
}

export function UpdateBuiltinPricing(): $CancellablePromise<$models.PricingUpdateResult> {
    return $Call.ByID(4017734004).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PricingBuiltinDetail.createFrom;
const $$createType1 = $models.PricingOverview.createFrom;
const $$createType2 = $models.PricingBuiltinPage.createFrom;
const $$createType3 = $models.PricingCustomRule.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.PricingMatchResult.createFrom;
const $$createType6 = $models.PricingUpdateResult.createFrom;
