// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreatePiProviderTemplate(template: $models.PiProviderTemplate): $CancellablePromise<void> {
    return $Call.ByID(2616012367, template);
}

export function DeletePiProviderTemplate(id: string): $CancellablePromise<void> {
    return $Call.ByID(1702610160, id);
}

export function DeleteRequestTemplate(id: string): $CancellablePromise<void> {
    return $Call.ByID(3634643075, id);
}

/**
 * DuplicateProvider 复制供应商配置，生成新的副本
 * 返回新创建的 Provider 对象
 */
export function DuplicateProvider(kind: string, sourceID: number): $CancellablePromise<$models.Provider | null> {
    return $Call.ByID(1332089125, kind, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListPiProviderTemplates(): $CancellablePromise<$models.PiProviderTemplate[]> {
    return $Call.ByID(2300603348).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListRequestTemplates(): $CancellablePromise<$models.ProviderRequestTemplate[]> {
    return $Call.ByID(3784656507).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadProviders 读取指定平台的 provider 列表。
 * 
 * 数据源是 provider 表（A1）。此前是读 JSON 文件并按 mtime+size 做缓存，
 * 那个缓存本身有竞态：Windows 上 mtime 精度约 1-2 秒，同一秒内
 * "写入 → 读取 → 再写入同长度内容" 会返回陈旧结果。改读数据库后
 * 不再需要这层缓存。
 */
export function LoadProviders(kind: string): $CancellablePromise<$models.Provider[]> {
    return $Call.ByID(3413098935, kind).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RenameProvider 改名 provider:事务更新 DB 中按 name 存储的历史数据,
 * 写入 48h alias 兜底 in-flight 请求,最后原子替换配置文件。
 * 
 * 校验规则:
 *   - newName 非空且 trim 后与 oldName 不等
 *   - 同 kind 下不存在其它 provider 用同名(当前 snapshot)
 *   - 48h 内 alias 表未占用该 newName
 *   - 该 provider_id 在 48h 内未 rename 过(禁止链式)
 */
export function RenameProvider(kind: string, id: number, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2498164164, kind, id, newName);
}

export function SaveProviders(kind: string, providers: $models.Provider[]): $CancellablePromise<void> {
    return $Call.ByID(1034860836, kind, providers);
}

/**
 * SaveProvidersWithRename 原子保存一次编辑中的字段更新和名称变更。
 * 该入口只允许更新现有 provider 集合，新增和删除仍使用 SaveProviders。
 */
export function SaveProvidersWithRename(kind: string, providerID: number, providers: $models.Provider[]): $CancellablePromise<void> {
    return $Call.ByID(391038558, kind, providerID, providers);
}

export function SaveRequestTemplate(template: $models.ProviderRequestTemplate): $CancellablePromise<$models.ProviderRequestTemplate> {
    return $Call.ByID(1141326029, template).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(194327613);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(291391407);
}

export function UpdatePiProviderTemplate(template: $models.PiProviderTemplate): $CancellablePromise<void> {
    return $Call.ByID(3644834370, template);
}

// Private type creation functions
const $$createType0 = $models.Provider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PiProviderTemplate.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ProviderRequestTemplate.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType0);
