// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReasonixSettingsService 管理 ~/.reasonix/config.json 的代理启停与直连应用。
 * 
 * 具体逻辑由 jsonProxyPlatform 通用实现承接（见 json_proxy_settings.go），
 * 这里只保留对外方法签名——它们注册进 Wails 绑定供前端调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplySingleProvider(providerID: number): $CancellablePromise<void> {
    return $Call.ByID(3133857807, providerID);
}

export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(4128756726);
}

export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(1882254311);
}

export function GetDirectAppliedProviderID(): $CancellablePromise<number | null> {
    return $Call.ByID(2485298760);
}

export function ProxyStatus(): $CancellablePromise<$models.ReasonixProxyStatus> {
    return $Call.ByID(726436320).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ReasonixProxyStatus.createFrom;
